name: 🐛 Bug report
description: Report any type of bug.
labels:
  - bug
body:
  - type: dropdown
    attributes:
      label: Type
      options:
        - New
        - Update
  - type: textarea
    attributes:
      label: Description
      description: Please tell us what happened.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      description: Please let us know your environment information.
    validations:
      required: true
