name: ❇️ Documentation
description: Anything about documents.
labels:
  - documentation
body:
  - type: textarea
    attributes:
      label: Description
      description: Details of the issue.
    validations:
      required: true
